name: rdr2_photo_exporter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window_windows: ^0.1.5
  filepicker_windows: ^2.0.9
  fluent_ui: ^4.7.3
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  path: ^1.8.3
  path_provider_windows: ^2.2.1
  win32: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
  win32: '5.0.7'

flutter:
  uses-material-design: true
