name: rdr2_photo_exporter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window_windows: ^0.1.5
  filepicker_windows:
    git:
      url: https://github.com/amarland/filepicker_windows.git
      ref: fad13ee214437385a1ebc884123c215af29f2cca
  fluent_ui: ^4.4.1
  flutter_bloc: ^8.1.2
  intl: ^0.18.0
  path: ^1.8.2
  path_provider_windows: ^2.1.5
  win32: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
